LINODE_IP=192.46.230.221
DB_NAME=peggy
DB_USER=deployer
DOCKER_HUB_USERNAME=tankwanghow
IMAGE_NAME=peggy
DOCKER_CONTAINER_NAME=peggy-app
DOMAIN_NAME=peggy.asia
PORT=8082
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=peggy.my.asia@gmail.com
MAIL_FROM=peggy.my.asia@gmail.com

