defmodule PeggyWeb.FarmLive.PromoteBatches do
  @moduledoc """
  Triage screen that surfaces batch animals whose age has crossed a
  per-farm promotion threshold.

  Three sections, generated by `Peggy.Animals.suggest_promotions/1`:

    * **Weaner → Grower** — bulk-promotable
    * **Grower → Finisher** — bulk-promotable
    * **Overdue finishers** — not promotable (no next stage); each row
      links to the existing single-batch departure flow on the animal
      detail page.

  Per-row checkboxes feed bulk "Apply selected" / "Apply all" actions
  routed through `Animals.promote_many/3`. The bulk call uses per-row
  semantics — one bad row reports an error without rolling back the
  successful ones.
  """
  use PeggyWeb, :live_view

  alias Peggy.Animals
  alias Peggy.Policy

  @impl true
  def render(assigns) do
    ~H"""
    <Layouts.app flash={@flash} current_scope={@current_scope}>
      <div class="mx-auto max-w-6xl">
        <div class="text-sm text-base-content/60 mb-1">
          <.link
            navigate={~p"/farms/#{@current_scope.farm.slug}/animals"}
            class="text-primary underline hover:text-primary/80"
          >
            ← {gettext("All animals")}
          </.link>
        </div>

        <.header>
          {gettext("Promote batch animals")}
          <:subtitle>
            {gettext(
              "Batches whose age has crossed your farm's promotion thresholds. Adjust thresholds in Settings → Breeding parameters."
            )}
          </:subtitle>
        </.header>

        <.section
          id="bucket-weaner"
          title={gettext("Weaner → Grower")}
          description={gettext("Weaners older than %{n} days from birth.", n: @thresholds.weaner)}
          entries={@suggestions.weaner_to_grower}
          target_stage="grower"
          can_manage={@can_manage}
          selected={@selected.weaner_to_grower}
          empty_text={gettext("No weaner batches due for promotion.")}
          farm_slug={@current_scope.farm.slug}
        />

        <.section
          id="bucket-grower"
          title={gettext("Grower → Finisher")}
          description={gettext("Growers older than %{n} days from birth.", n: @thresholds.grower)}
          entries={@suggestions.grower_to_finisher}
          target_stage="finisher"
          can_manage={@can_manage}
          selected={@selected.grower_to_finisher}
          empty_text={gettext("No grower batches due for promotion.")}
          farm_slug={@current_scope.farm.slug}
        />

        <.overdue_section
          id="bucket-overdue"
          entries={@suggestions.finisher_overdue}
          threshold_days={@thresholds.overdue}
          farm_slug={@current_scope.farm.slug}
          can_depart={@can_depart}
        />
      </div>
    </Layouts.app>
    """
  end

  attr :id, :string, required: true
  attr :title, :string, required: true
  attr :description, :string, required: true
  attr :entries, :list, required: true
  attr :target_stage, :string, required: true
  attr :can_manage, :boolean, required: true
  attr :selected, :any, required: true
  attr :empty_text, :string, required: true
  attr :farm_slug, :string, required: true

  defp section(assigns) do
    ~H"""
    <section id={@id} class="mt-8">
      <div class="flex items-end justify-between gap-3">
        <div>
          <h2 class="text-lg font-semibold">
            {@title}
            <span class="badge badge-sm badge-ghost ml-2">{length(@entries)}</span>
          </h2>
          <p class="text-sm text-base-content/60">{@description}</p>
        </div>

        <div :if={@can_manage and @entries != []} class="flex gap-2">
          <button
            type="button"
            class="btn btn-sm"
            phx-click="apply_selected"
            phx-value-bucket={@id}
            phx-value-stage={@target_stage}
            disabled={MapSet.size(@selected) == 0}
          >
            {gettext("Apply selected (%{n})", n: MapSet.size(@selected))}
          </button>
          <button
            type="button"
            class="btn btn-sm btn-primary"
            phx-click="apply_all"
            phx-value-bucket={@id}
            phx-value-stage={@target_stage}
            data-confirm={
              gettext("Promote all %{n} batches to %{stage}?",
                n: length(@entries),
                stage: @target_stage
              )
            }
          >
            {gettext("Apply all")}
          </button>
        </div>
      </div>

      <div :if={@entries == []} class="mt-3 text-sm text-base-content/60">
        {@empty_text}
      </div>

      <table :if={@entries != []} class="table w-full mt-3">
        <thead class="text-left text-base-content/60">
          <tr>
            <th class="py-1 w-8">
              <input
                type="checkbox"
                class="checkbox checkbox-sm"
                phx-click="toggle_all"
                phx-value-bucket={@id}
                checked={MapSet.size(@selected) == length(@entries) and @entries != []}
                disabled={not @can_manage}
              />
            </th>
            <th class="py-1">{gettext("Tag")}</th>
            <th class="py-1">{gettext("Qty")}</th>
            <th class="py-1">{gettext("Born")}</th>
            <th class="py-1">{gettext("Age (d)")}</th>
            <th class="py-1">{gettext("Last weaned")}</th>
          </tr>
        </thead>
        <tbody>
          <tr
            :for={entry <- @entries}
            class="border-t border-base-200 align-middle"
          >
            <td class="py-0.5">
              <input
                type="checkbox"
                class="checkbox checkbox-sm"
                phx-click="toggle_row"
                phx-value-bucket={@id}
                phx-value-id={entry.animal.id}
                checked={MapSet.member?(@selected, entry.animal.id)}
                disabled={not @can_manage}
              />
            </td>
            <td class="py-0.5 font-mono">
              <.link
                navigate={~p"/farms/#{@farm_slug}/animals/#{entry.animal.id}"}
                class="text-primary underline hover:text-primary/80"
              >
                {entry.animal.ear_tag}
              </.link>
            </td>
            <td class="py-0.5">{entry.animal.quantity}</td>
            <td class="py-0.5 font-mono text-base-content/70">{entry.animal.dob}</td>
            <td class="py-0.5 font-mono">{entry.age_days}</td>
            <td class="py-0.5 font-mono text-base-content/70">
              {entry.last_weaned_at || "—"}
            </td>
          </tr>
        </tbody>
      </table>
    </section>
    """
  end

  attr :id, :string, required: true
  attr :entries, :list, required: true
  attr :threshold_days, :integer, required: true
  attr :farm_slug, :string, required: true
  attr :can_depart, :boolean, required: true

  defp overdue_section(assigns) do
    ~H"""
    <section id={@id} class="mt-8">
      <div class="flex items-end justify-between gap-3">
        <div>
          <h2 class="text-lg font-semibold">
            {gettext("Overdue finishers")}
            <span class="badge badge-sm badge-warning ml-2">{length(@entries)}</span>
          </h2>
          <p class="text-sm text-base-content/60">
            {gettext(
              "Finishers older than %{n} days from birth. These should already have left the farm.",
              n: @threshold_days
            )}
          </p>
        </div>

        <button
          :if={@can_depart and @entries != []}
          type="button"
          class="btn btn-sm btn-warning"
          phx-click="depart_all_overdue"
          data-confirm={
            gettext("Mark all %{n} overdue finisher batches as sold today?", n: length(@entries))
          }
        >
          {gettext("Mark all sold")}
        </button>
      </div>

      <div :if={@entries == []} class="mt-3 text-sm text-base-content/60">
        {gettext("No overdue finishers.")}
      </div>

      <table :if={@entries != []} class="table w-full mt-3">
        <thead class="text-left text-base-content/60">
          <tr>
            <th class="py-1">{gettext("Tag")}</th>
            <th class="py-1">{gettext("Qty")}</th>
            <th class="py-1">{gettext("Born")}</th>
            <th class="py-1">{gettext("Age (d)")}</th>
            <th class="py-1">{gettext("Last weaned")}</th>
            <th class="py-1 w-44">{gettext("Action")}</th>
          </tr>
        </thead>
        <tbody>
          <tr
            :for={entry <- @entries}
            class="border-t border-base-200 align-middle"
          >
            <td class="py-0.5 font-mono">
              <.link
                navigate={~p"/farms/#{@farm_slug}/animals/#{entry.animal.id}"}
                class="text-primary underline hover:text-primary/80"
              >
                {entry.animal.ear_tag}
              </.link>
            </td>
            <td class="py-0.5">{entry.animal.quantity}</td>
            <td class="py-0.5 font-mono text-base-content/70">{entry.animal.dob}</td>
            <td class="py-0.5 font-mono text-warning">{entry.age_days}</td>
            <td class="py-0.5 font-mono text-base-content/70">
              {entry.last_weaned_at || "—"}
            </td>
            <td class="py-0.5 flex gap-1">
              <button
                :if={@can_depart}
                type="button"
                class="btn btn-xs btn-warning"
                phx-click="depart_one"
                phx-value-id={entry.animal.id}
                data-confirm={
                  gettext("Mark batch %{tag} as sold today (qty %{qty})?",
                    tag: entry.animal.ear_tag,
                    qty: entry.animal.quantity
                  )
                }
              >
                {gettext("Mark sold")}
              </button>
              <.link
                navigate={~p"/farms/#{@farm_slug}/animals/#{entry.animal.id}"}
                class="btn btn-xs"
              >
                {gettext("Detail")}
              </.link>
            </td>
          </tr>
        </tbody>
      </table>
    </section>
    """
  end

  @impl true
  def mount(_params, _session, socket) do
    scope = socket.assigns.current_scope
    farm = scope.farm

    {:ok,
     socket
     |> assign(
       can_manage: Policy.can?(scope, :manage_animals),
       can_depart: Policy.can?(scope, :record_movement),
       thresholds: %{
         weaner: farm.weaner_to_grower_days,
         grower: farm.grower_to_finisher_days,
         overdue: farm.finisher_overdue_days
       },
       selected: %{
         weaner_to_grower: MapSet.new(),
         grower_to_finisher: MapSet.new()
       }
     )
     |> assign_suggestions()}
  end

  @impl true
  def handle_event("toggle_row", %{"bucket" => bucket, "id" => id}, socket) do
    bucket_key = bucket_key!(bucket)
    id = String.to_integer(id)
    set = Map.fetch!(socket.assigns.selected, bucket_key)

    set =
      if MapSet.member?(set, id), do: MapSet.delete(set, id), else: MapSet.put(set, id)

    {:noreply, update(socket, :selected, &Map.put(&1, bucket_key, set))}
  end

  def handle_event("toggle_all", %{"bucket" => bucket}, socket) do
    bucket_key = bucket_key!(bucket)
    entries = Map.fetch!(socket.assigns.suggestions, bucket_key)
    current = Map.fetch!(socket.assigns.selected, bucket_key)
    all_ids = MapSet.new(Enum.map(entries, & &1.animal.id))

    set =
      if MapSet.size(current) == MapSet.size(all_ids), do: MapSet.new(), else: all_ids

    {:noreply, update(socket, :selected, &Map.put(&1, bucket_key, set))}
  end

  def handle_event("apply_selected", %{"bucket" => bucket, "stage" => stage}, socket) do
    bucket_key = bucket_key!(bucket)
    ids = socket.assigns.selected |> Map.fetch!(bucket_key) |> MapSet.to_list()
    apply_promotion(socket, ids, stage)
  end

  def handle_event("apply_all", %{"bucket" => bucket, "stage" => stage}, socket) do
    bucket_key = bucket_key!(bucket)
    ids = socket.assigns.suggestions |> Map.fetch!(bucket_key) |> Enum.map(& &1.animal.id)
    apply_promotion(socket, ids, stage)
  end

  def handle_event("depart_one", %{"id" => id}, socket) do
    apply_departure(socket, [String.to_integer(id)])
  end

  def handle_event("depart_all_overdue", _, socket) do
    ids = Enum.map(socket.assigns.suggestions.finisher_overdue, & &1.animal.id)
    apply_departure(socket, ids)
  end

  defp apply_promotion(socket, [], _stage) do
    {:noreply, put_flash(socket, :error, gettext("Nothing selected."))}
  end

  defp apply_promotion(socket, ids, stage) do
    if socket.assigns.can_manage do
      result = Animals.promote_many(socket.assigns.current_scope, ids, stage)

      flash_msg =
        case {length(result.ok), length(result.errors)} do
          {n, 0} -> gettext("Promoted %{n} batches.", n: n)
          {0, m} -> gettext("Failed to promote %{m} batches.", m: m)
          {n, m} -> gettext("Promoted %{n} batches, %{m} failed.", n: n, m: m)
        end

      flash_kind = if result.errors == [], do: :info, else: :error

      {:noreply,
       socket
       |> put_flash(flash_kind, flash_msg)
       |> assign(
         selected: %{
           weaner_to_grower: MapSet.new(),
           grower_to_finisher: MapSet.new()
         }
       )
       |> assign_suggestions()}
    else
      {:noreply, put_flash(socket, :error, gettext("Not authorized."))}
    end
  end

  defp apply_departure(socket, []) do
    {:noreply, put_flash(socket, :error, gettext("Nothing to depart."))}
  end

  defp apply_departure(socket, ids) do
    if socket.assigns.can_depart do
      result = Animals.depart_many(socket.assigns.current_scope, ids, "sale")

      flash_msg =
        case {length(result.ok), length(result.errors)} do
          {n, 0} -> gettext("Marked %{n} batches sold.", n: n)
          {0, m} -> gettext("Failed to depart %{m} batches.", m: m)
          {n, m} -> gettext("Marked %{n} sold, %{m} failed.", n: n, m: m)
        end

      flash_kind = if result.errors == [], do: :info, else: :error

      {:noreply,
       socket
       |> put_flash(flash_kind, flash_msg)
       |> assign_suggestions()}
    else
      {:noreply, put_flash(socket, :error, gettext("Not authorized."))}
    end
  end

  defp assign_suggestions(socket) do
    suggestions = Animals.suggest_promotions(socket.assigns.current_scope)
    assign(socket, :suggestions, suggestions)
  end

  defp bucket_key!("bucket-weaner"), do: :weaner_to_grower
  defp bucket_key!("bucket-grower"), do: :grower_to_finisher
end
