defmodule Peggy.Repo.Migrations.DropAutoGeneratedBreedingTasks do
  use Ecto.Migration

  # The Scheduler used to auto-create `wean` and `farrow` tasks that
  # duplicated the Gestating / Lactating breeding worklists. The
  # scheduler is gone and those kinds are no longer in the schema's
  # enum, so any leftover rows would fail validation on the next
  # changeset write. Drop them.
  def up do
    execute("DELETE FROM tasks WHERE kind IN ('wean', 'farrow')")
  end

  def down do
    # Auto-generated noise — nothing meaningful to restore.
    :ok
  end
end
